import Link from 'next/link';
import { HeartHandshake, Users, Landmark, UserCheck, ListChecks, FileCheck2, AlertTriangle, ArrowRight } from 'lucide-react';
import styles from '../tools.module.css';

const cycle=[
  ['01','Confirm the legal position','Start with the current ownership schedule, trust order, trustee list and any later changes.'],
  ['02','Choose the right structure','Be clear why the trust is needed and which trust type matches that purpose.'],
  ['03','Engage owners properly','Prepare hui notices, agendas, attendance, voting information and signed minutes.'],
  ['04','Confirm trustees','Record suitability, consent, conflicts and governance responsibilities.'],
  ['05','Prepare the Court matter','Use current forms and attach the ownership, minutes, resolutions and consents required.'],
  ['06','Govern after the order','Maintain registers, meetings, decisions, actions and annual records after establishment.']
];

export default function TrustsPage(){return <main className={styles.page}>
  <section className={styles.hero}><div className={styles.heroMain}><span className={styles.eyebrow}>TRUSTS & GOVERNANCE</span><h1>Set up the structure — then govern it properly</h1><p>This workspace separates establishing or changing a trust from the ongoing work of good governance. The legal order is only the beginning.</p><div className={styles.quickActions}><Link href="/workspace/documents">Governance documents</Link><Link href="/workspace/applications">Trust applications</Link></div></div><aside className={styles.heroAside}><div className={styles.metric}><span>Governance cycle</span><strong>6</strong></div><div className={styles.metric}><span>Focus</span><strong style={{fontSize:16}}>Owners + trustees</strong></div><div className={styles.metric}><span>Ongoing</span><strong style={{fontSize:16}}>Records + decisions</strong></div></aside></section>
  <div className={styles.toolbar}><div><h2>What kind of trust work are you doing?</h2><p>Choose the workstream before you start gathering documents.</p></div></div>
  <div className={styles.pipeline}><div className={styles.pipeCard}><Users size={19}/><b style={{fontSize:14,marginTop:9}}>Whānau trust</b><span>Aggregate family interests and define the purpose clearly.</span></div><div className={styles.pipeCard}><Landmark size={19}/><b style={{fontSize:14,marginTop:9}}>Ahu whenua / whenua tōpū</b><span>Collective land management with clear governance.</span></div><div className={styles.pipeCard}><UserCheck size={19}/><b style={{fontSize:14,marginTop:9}}>Trustee changes</b><span>Appointments, resignations, deaths and replacements.</span></div><div className={styles.pipeCard}><ListChecks size={19}/><b style={{fontSize:14,marginTop:9}}>Ongoing governance</b><span>Meetings, registers, reporting and action tracking.</span></div></div>
  <div className={styles.toolbar}><div><h2>Governance pathway</h2><p>Move from legal position to owner engagement, Court preparation and ongoing administration.</p></div></div>
  <div className={styles.grid2}><section className={styles.panel}><div className={styles.recordList}>{cycle.map(([n,t,d])=><article key={n} className={styles.record}><div style={{display:'flex',gap:12}}><span className={styles.status}>{n}</span><div><strong>{t}</strong><p>{d}</p></div></div></article>)}</div></section><aside className={styles.panel}><div className={styles.panelTitle}><span><FileCheck2 size={18}/></span><h3>Governance pack</h3></div><div className={styles.recordList}>{['Current trust order or ownership schedule','Current/proposed trustee details','Owner contact information','Trust objectives','Hui notices, minutes and resolutions','Financial or land-management records'].map(x=><div className={styles.record} key={x}><strong>{x}</strong></div>)}</div><div className={styles.notice} style={{marginTop:16}}><AlertTriangle size={16}/>Disputed ownership, trustee conflict or unclear authority should be escalated for qualified legal advice before decisions are implemented.</div></aside></div>
  <div className={styles.toolbar}><div><h2>Move the trust matter forward</h2><p>Create the application record only when the purpose, owners and trustee information are clear.</p></div></div><Link href="/workspace/applications" className={styles.primary}>Prepare trust application <ArrowRight size={14}/></Link>
</main>}
