import Link from 'next/link';
import { ArrowLeft, ArrowUpRight, BookOpen, ShieldCheck, Users, House, FileText, ExternalLink, Scale } from 'lucide-react';
import styles from './resources.module.css';

const groups=[
{title:'Māori Land Court',description:'Use these sources for current Court guidance, forms, succession information and accepted submission channels.',items:[
{title:'Application forms',description:'Official Māori Land Court forms and application information. Check the current version before preparing a filing.',url:'https://www.xn--morilandcourt-wqb.govt.nz/en/our-application-process/come-in-apply-to-the-court/application-forms',source:'Māori Land Court',icon:FileText},
{title:'Application guides',description:'Plain-language official guides covering succession, partition and Māori land trust pathways.',url:'https://www.xn--morilandcourt-wqb.govt.nz/en/our-application-process/application-guides',source:'Māori Land Court',icon:BookOpen},
{title:'Succession guidance',description:'Official information about becoming a landowner through succession and the evidence that may be required.',url:'https://www.xn--morilandcourt-wqb.govt.nz/en/maori-land/becoming-a-landowner/succession',source:'Māori Land Court',icon:Users},
{title:'Submit an application',description:'Official submission information, including Pātaka Whenua and other accepted channels.',url:'https://www.xn--morilandcourt-wqb.govt.nz/en/our-application-process/come-in-apply-to-the-court/submit-an-application',source:'Māori Land Court',icon:ArrowUpRight}
]},
{title:'Housing on whenua Māori',description:'Current public guidance for papakāinga, whenua Māori housing support and the legal settings that can affect development.',items:[
{title:'Small-scale papakāinga new builds',description:'Te Puni Kōkiri guidance on support for small-scale papakāinga, infrastructure, capital funding and related resources.',url:'https://www.tpk.govt.nz/en/nga-putea-me-nga-ratonga/maori-housing/new-builds-small-scale-papakainga',source:'Te Puni Kōkiri',icon:House},
{title:'Māori housing support',description:'Te Puni Kōkiri’s current Māori housing hub, including new builds, repairs and support available through other agencies.',url:'https://www.tpk.govt.nz/en/nga-putea-me-nga-ratonga/maori-housing',source:'Te Puni Kōkiri',icon:House},
{title:'Whenua Māori law changes affecting housing',description:'Background on statutory changes supporting housing on whenua Māori, Māori land trusts and related matters.',url:'https://www.tpk.govt.nz/en/a-matou-whakaarotau/te-ao-maori/te-ture-whenua-maori-act-1993/new-laws-for-matters-related-to-whenua-maori',source:'Te Puni Kōkiri',icon:Scale}
]}
];

export default function Resources(){return <main><header className="site-header"><Link href="/" className="brand"><span className="brand-mark">T<span>Ā</span></span><span><strong>TE AO HOU</strong><small>WHĀNAU · WHENUA · FUTURE</small></span></Link><Link href="/workspace" className="header-action">Whānau workspace <ArrowUpRight size={17}/></Link></header><section className="section" style={{paddingTop:45,minHeight:'75vh'}}><Link href="/workspace" className="text-link"><ArrowLeft size={16}/> Back to workspace</Link><div className={styles.hero}><div className={styles.intro}><span className={styles.kicker}>OFFICIAL INFORMATION</span><h1 className="workspace-title" style={{fontSize:45}}>Resources & guidance</h1><p className="workspace-lead">Use the official source first. Te Ao Hou can help organise what you need, but forms, eligibility, fees, funding settings and legal requirements can change.</p></div><aside className={styles.summary}><ShieldCheck size={22}/><h3>Source-controlled guidance</h3><p>Each resource identifies the issuing organisation. Current requirements should be checked again at the point of application, funding assessment or filing.</p></aside></div>{groups.map(group=><section className={styles.group} key={group.title}><div className={styles.groupHead}><div><span className={styles.kicker}>VERIFIED STARTING POINTS</span><h2>{group.title}</h2></div><p>{group.description}</p></div><div className={styles.grid}>{group.items.map(item=>{const Icon=item.icon;return <a className={styles.card} href={item.url} target="_blank" rel="noopener noreferrer" key={item.title}><div className={styles.icon}><Icon size={21}/></div><h3>{item.title}</h3><p>{item.description}</p><span className={styles.meta}>{item.source} · Reviewed 11 September 2026</span><span className={styles.link}>Open official source <ExternalLink size={15}/></span></a>})}</div></section>)}<div className={styles.notice}><ShieldCheck size={18}/><span>Te Ao Hou is an independent support platform. It does not issue Māori Land Court orders, grant council consent, provide legal advice, or approve finance. Those decisions remain with the relevant authorised body or professional.</span></div></section></main>}
