import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowRight, ShieldCheck, FileText, House, Users, LandPlot, HeartHandshake, Compass, FolderOpen, BriefcaseBusiness, Search, Scale, CheckCircle2, Building2, WalletCards, Route, MapPinned, ClipboardCheck, ExternalLink, AlertTriangle, BookOpen } from 'lucide-react';
import styles from './section.module.css';

type Stage={title:string,description:string,tags?:string[],checks?:string[]};
type Goal={title:string,description:string,icon:string,href?:string};
type SectionData={title:string,subtitle:string,description:string,icon:string,summary:string,goals:Goal[],stages:Stage[],prepare:string[],decisions:string[],resources:{label:string,href:string}[],warning?:string};

const iconMap={FileText,House,Users,LandPlot,HeartHandshake,Compass,FolderOpen,BriefcaseBusiness,Search,Scale,Building2,WalletCards,Route,MapPinned,ClipboardCheck,BookOpen};

const sections:Record<string,SectionData>={
plan:{title:'My Whenua Plan',subtitle:'A pathway built around your goal',icon:'Compass',description:'Choose what you want to achieve and see the stages that may sit between where you are now and your end goal.',summary:'Your plan starts with the outcome you want, then works backwards through ownership, authority, evidence, Court processes, feasibility, funding and delivery.',goals:[
{title:'Build a home on whānau land',description:'Work through ownership, authority to occupy or build, services, consents, funding and construction readiness.',icon:'House',href:'/workspace/housing'},
{title:'Succeed to Māori land interests',description:'Identify the deceased owner, whakapapa, rightful successors, evidence and the appropriate Court application.',icon:'Users',href:'/workspace/succession'},
{title:'Understand what whenua we own',description:'Start with block names, ownership records, trusts, orders and the people connected to the whenua.',icon:'LandPlot',href:'/workspace/whenua'},
{title:'Set up or change a trust',description:'Understand trust purpose, owner support, trustee responsibilities, governance records and Court requirements.',icon:'HeartHandshake',href:'/workspace/trusts'}],stages:[
{title:'Define the outcome',description:'Be clear about what success looks like: succession completed, a home built, a trust established, access secured or ownership understood.',tags:['Goal'],checks:['Write down the outcome in plain language','Identify who in the whānau is involved','Record any known deadlines or hearings']},
{title:'Confirm whenua and ownership',description:'Identify the land block and current legal ownership or trust arrangements before planning the next move.',tags:['Whenua','Records'],checks:['Find the block name or legal description','Check current owners and trustees','Locate relevant existing Court orders']},
{title:'Confirm authority and legal pathway',description:'Work out what authority is needed and whether the pathway involves succession, occupation, trust orders, access or another statutory process.',tags:['Authority','Court'],checks:['Identify the decision-maker','Identify the required application or order','Flag any dispute or legal complexity for qualified advice']},
{title:'Prepare evidence and whānau support',description:'Collect the documents, whakapapa, consents, minutes and professional evidence needed for the pathway.',tags:['Evidence','Whānau'],checks:['Create an evidence checklist','Identify missing documents','Record hui decisions and consents where required']},
{title:'Progress feasibility and funding',description:'For development goals, test site, infrastructure, consent and funding feasibility before committing to construction.',tags:['Feasibility','Funding'],checks:['Check access and services','Understand planning/building requirements','Assess funding readiness']},
{title:'Complete the formal process',description:'Submit through the correct authorised channel, respond to requests for information, attend hearings where required and complete post-order actions.',tags:['Submission','Completion'],checks:['Use current official forms and guidance','Track communications and deadlines','Store final orders and update governance records']}
],prepare:['Land block name or location','Names of current or previous owners','Known whakapapa connection','Existing Court orders or trust documents','Your intended outcome'],decisions:['Do you already hold an interest?','Is succession required first?','Do you need authority to occupy or build?','Is there an existing trust?','Is the matter disputed or complex?'],resources:[{label:'Māori Land Court application guides',href:'https://www.xn--morilandcourt-wqb.govt.nz/en/our-application-process/application-guides'},{label:'Pātaka Whenua / submit an application',href:'https://www.xn--morilandcourt-wqb.govt.nz/en/our-application-process/come-in-apply-to-the-court/submit-an-application'}]},
whenua:{title:'Understand your whenua',subtitle:'Find your connection',icon:'LandPlot',description:'Build a clear picture of the whenua, the current ownership structure, the people connected to it and the orders that affect it.',summary:'This page is designed to answer the first practical question most whānau have: “What land is this, who owns it now, and what do I need to look at next?”',goals:[
{title:'Find a land block',description:'Use known names, locations, whānau names and official records to narrow down the whenua.',icon:'Search'},{title:'Understand ownership',description:'Read current ownership interests, trustees and ownership structures before taking action.',icon:'Users'},{title:'Understand existing orders',description:'Identify trust, occupation, partition, access or other orders that may shape what can happen next.',icon:'Scale'},{title:'Map the next step',description:'Once the record is understood, move into succession, trust, access, housing or another relevant pathway.',icon:'Route'}],stages:[
{title:'Start with what your whānau knows',description:'Gather block names, place names, owner names, marae or hapū references and any old documents.',checks:['Record every spelling variation','Ask whānau for old orders, rates notices or correspondence','Note where the whenua is located']},
{title:'Search official land records',description:'Use official Māori Land Court services and records to confirm the legal block and ownership information.',tags:['Official records'],checks:['Confirm the block name','Check ownership and trustee information','Save the relevant record references']},
{title:'Read the ownership structure',description:'Determine whether interests are held individually, through a whānau trust, ahu whenua trust, whenua tōpū trust or another arrangement.',tags:['Ownership'],checks:['Identify owners and trustees','Identify deceased owners','Check whether succession appears outstanding']},
{title:'Identify orders and restrictions',description:'Look for existing orders affecting occupation, access, partition, status, trusts or other legal rights.',tags:['Orders'],checks:['List relevant orders','Note dates and Court references','Identify anything that conflicts with the whānau goal']},
{title:'Choose the next pathway',description:'Use the record to identify whether the next step is succession, governance, housing, access or another formal application.',tags:['Next step']}
],prepare:['Approximate location','Known block or farm name','Names of owners or tūpuna','Any Court minute, order or title reference','Marae, hapū or whānau connection'],decisions:['Is the correct land block confirmed?','Are there deceased owners still on the title?','Is there an existing trust?','Are there occupation or access orders?','Does the record match the whānau understanding?'],resources:[{label:'Māori Land Court — Māori land information',href:'https://www.xn--morilandcourt-wqb.govt.nz/en/maori-land'},{label:'Māori Land Court — application forms',href:'https://www.xn--morilandcourt-wqb.govt.nz/en/our-application-process/come-in-apply-to-the-court/application-forms'}]},
succession:{title:'Succession pathway',subtitle:'Your connection through generations',icon:'Users',description:'Work through the practical steps involved when Māori land interests need to pass from a deceased owner to the people entitled to succeed.',summary:'Succession is not simply “putting one name on the land.” The Court identifies the relevant interests and rightful successors, and the evidence needs to support that whakapapa and entitlement.',goals:[
{title:'Identify the deceased owner',description:'Confirm the person, their land interests and whether previous succession has already occurred.',icon:'Search'},{title:'Build the whakapapa record',description:'Record the family line and all people who may be entitled to succeed.',icon:'Users'},{title:'Prepare the evidence pack',description:'Gather death, will, whakapapa, whāngai, partner and trust material where relevant.',icon:'FolderOpen'},{title:'Prepare for application',description:'Match the circumstances to the current official succession process before submission.',icon:'ClipboardCheck'}],stages:[
{title:'Confirm the deceased owner and interests',description:'Establish which owner has died and which Māori land interests are affected.',tags:['Owner','Interests'],checks:['Confirm full legal name and aliases','Find relevant land blocks','Check whether any interests were already succeeded']},
{title:'Identify all rightful successors',description:'Build the whakapapa carefully so the application does not omit people who may be entitled.',tags:['Whakapapa'],checks:['Record children and descendants','Record relevant whāngai circumstances','Check whether a surviving partner may have rights']},
{title:'Collect supporting evidence',description:'Gather current official evidence required for the circumstances of the succession.',tags:['Evidence'],checks:['Death certificate','Original or certified will if one exists','Whakapapa and family contact information','Partner, whāngai or trust documents where applicable']},
{title:'Decide how interests should be held',description:'Consider whether successors will take interests directly or whether an appropriate trust application is also proposed.',tags:['Decision'],checks:['Discuss options with all affected people','Record trustee consents if a trust is proposed','Prepare hui minutes where relevant']},
{title:'Prepare and submit the application',description:'Use current Māori Land Court guidance and Pātaka Whenua or another accepted submission channel.',tags:['Application'],checks:['Use the current form/process','Check all supporting documents','Keep a complete copy of the submitted application']},
{title:'Track hearing, decision and post-order work',description:'Respond to Court requests, attend any required hearing and retain final orders.',tags:['Court','Completion'],checks:['Track correspondence','Record hearing dates','Store final orders and update whānau records']}
],prepare:['Deceased owner’s full name','Death certificate','Will, if one exists','Whakapapa showing all possible successors','Known Māori land interests','Relevant trust or whāngai information'],decisions:['Has succession already been completed for some interests?','Who are all rightful successors?','Does a surviving partner hold relevant rights?','Are whāngai circumstances involved?','Should a whānau trust be considered?'],resources:[{label:'Māori Land Court — succession',href:'https://www.xn--morilandcourt-wqb.govt.nz/en/maori-land/becoming-a-landowner/succession'},{label:'Māori Land Court — application guides',href:'https://www.xn--morilandcourt-wqb.govt.nz/en/our-application-process/application-guides'}],warning:'Contested whakapapa, wills, capacity issues, competing claims or complex estates should be escalated for qualified legal advice. Te Ao Hou should support preparation and case management, not make legal determinations.'},
housing:{title:'Housing & development',subtitle:'A place to call home',icon:'House',description:'Turn a housing goal into a staged whenua-development pathway covering authority, site feasibility, council requirements, funding and construction readiness.',summary:'The key is sequence. Before spending heavily on plans or construction, confirm the legal right to use the whenua and whether the site can actually support the proposed development.',goals:[
{title:'Confirm authority to build',description:'Understand who owns or administers the whenua and what legal authority is required to occupy or develop it.',icon:'Scale'},{title:'Check the site',description:'Review access, services, wastewater, water, power, natural hazards and practical constraints.',icon:'MapPinned'},{title:'Understand consents',description:'Identify the relevant district plan, resource consent and building consent requirements with the appropriate council.',icon:'Building2'},{title:'Prepare for funding',description:'Organise ownership, authority, valuation, plans, costs and lender information before seeking finance.',icon:'WalletCards'}],stages:[
{title:'Confirm land interests and authority',description:'Do not begin from house plans. Begin with the legal status of the whenua and the authority to occupy, licence, lease or otherwise develop.',tags:['Authority'],checks:['Confirm block and ownership','Identify trustees or administrators','Identify occupation/licence/lease requirements']},
{title:'Complete early site feasibility',description:'Establish whether access, services and physical conditions support the intended build.',tags:['Site'],checks:['Legal and physical access','Water and wastewater options','Power and telecommunications','Flood, slope and other hazard checks']},
{title:'Define the development concept',description:'Set the number of homes, intended occupants, approximate footprint, servicing approach and staged budget.',tags:['Concept'],checks:['Define who will live there','Set indicative build scope','Identify professionals needed']},
{title:'Confirm planning and consent pathway',description:'Check the relevant local authority requirements for the specific site and development.',tags:['Council'],checks:['District plan / zoning review','Resource consent assessment','Building consent requirements','Engineering or specialist reports if required']},
{title:'Build a finance-ready pack',description:'Bring together authority, site information, plans, budget, valuation and borrower information for the relevant funding pathway.',tags:['Funding'],checks:['Project budget','Evidence of authority','Plans/specifications','Borrower affordability and deposit information where applicable']},
{title:'Procure and build',description:'Only after legal, consent and funding gates are satisfied should the project move into contracted construction and completion.',tags:['Delivery'],checks:['Signed contracts','Approved consents','Confirmed funding','Insurance and completion documentation']}
],prepare:['Land block and ownership record','Existing occupation/licence/lease orders','Site address or map reference','Known access and utility information','Approximate build goal and household','Indicative budget'],decisions:['Who has authority to approve occupation or development?','Is separate title or security required by a lender?','Can the site be serviced?','What council approvals apply?','Is the project financially feasible?'],resources:[{label:'Start with your whenua record',href:'/workspace/whenua'},{label:'Open Te Ao Hou resource library',href:'/resources'}],warning:'Planning, building, engineering and lending requirements depend on the particular whenua, council, ownership structure and funding provider. Te Ao Hou should record verified requirements for each case rather than assume one national pathway.'},
trusts:{title:'Trusts & governance',subtitle:'Working together for the generations',icon:'HeartHandshake',description:'Understand trust purpose, owner participation, trustee responsibilities and the governance records needed to administer Māori land collectively.',summary:'A trust is not just an application. It creates an ongoing governance structure, so the system needs to support both establishment and the work that comes after the order.',goals:[],stages:[{title:'Confirm current ownership and existing trusts',description:'Understand the whenua and whether a trust already exists.'},{title:'Define purpose and structure',description:'Identify the proposed trust type, objectives and beneficiaries.'},{title:'Engage owners and proposed trustees',description:'Record hui, owner support, trustee consents and concerns.'},{title:'Prepare the Court pathway',description:'Use current forms and supporting material for establishment or variation.'},{title:'Maintain governance after the order',description:'Store orders, trustee details, meetings, resolutions and accountability records.'}],prepare:['Ownership schedule','Existing trust order','Proposed trustees','Trust objectives','Hui records and owner support'],decisions:['Is a trust already in place?','What trust structure fits the purpose?','Who should serve as trustees?','What governance rules are needed?'],resources:[{label:'Māori Land Court application guides',href:'https://www.xn--morilandcourt-wqb.govt.nz/en/our-application-process/application-guides'}]},
applications:{title:'Applications',subtitle:'Understand the application pathways',icon:'FileText',description:'Browse common Māori Land Court matters and understand what information should be collected before using an official application process.',summary:'This workspace will eventually route each case to a structured checklist based on the application type and current official requirements.',goals:[],stages:[{title:'Identify the legal issue',description:'Define the order, change or determination being sought.'},{title:'Select the correct current process',description:'Match the matter to the current Court form or application pathway.'},{title:'Collect evidence and consents',description:'Build the supporting bundle before submission.'},{title:'Quality review',description:'Check names, blocks, exhibits, consents and supporting records.'},{title:'Submit and track',description:'Use an accepted Court channel and track all communications and deadlines.'}],prepare:['What outcome is being sought','Land block details','Affected owners/trustees','Existing orders','Supporting evidence'],decisions:['Is this the correct application type?','Are all affected people identified?','Is legal advice required?'],resources:[{label:'Current Māori Land Court application forms',href:'https://www.xn--morilandcourt-wqb.govt.nz/en/our-application-process/come-in-apply-to-the-court/application-forms'}]},
documents:{title:'My documents',subtitle:'Keep your evidence organised',icon:'FolderOpen',description:'Plan the evidence bundle that will sit behind each matter. Secure upload and sharing will be enabled only with the dedicated Te Ao Hou data environment.',summary:'Until private storage is provisioned, this page shows the document structure without accepting personal information.',goals:[],stages:[{title:'Create the evidence checklist',description:'List the documents required for the particular pathway.'},{title:'Collect originals and certified copies where required',description:'Track what has been received and what remains outstanding.'},{title:'Review document quality',description:'Check names, dates, signatures and legibility.'},{title:'Prepare the case bundle',description:'Organise evidence in the same sequence as the application and case notes.'}],prepare:['Identity records where required','Court orders','Whakapapa records','Consents and minutes','Professional reports'],decisions:['Is the document current?','Does it relate to the correct person/block?','Does it need certification?'],resources:[{label:'Application resources',href:'/resources'}]},
operations:{title:'Operations',subtitle:'Jackson’s service workspace',icon:'BriefcaseBusiness',description:'Define the daily case-management flow for triage, assignments, evidence, referrals, appointments, communication and completion.',summary:'The public preview does not expose client data. The operational model is being built so the secure back office can be connected once Te Ao Hou has its own authentication and database.',goals:[],stages:[{title:'Triage',description:'Identify the whānau goal, urgency, jurisdiction and conflicts.'},{title:'Assign',description:'Allocate a case owner and establish tasks and due dates.'},{title:'Prepare',description:'Collect and review evidence and identify professional referrals.'},{title:'Review',description:'Quality-check the pathway before formal action.'},{title:'Track',description:'Record submissions, communications, hearings and decisions.'},{title:'Close and maintain',description:'Complete post-order actions and retain the governance record.'}],prepare:['Case goal','Client authority/consent','Conflict check','Evidence status','Due dates'],decisions:['Is the service within scope?','Who owns the case?','Does this require legal or specialist referral?'],resources:[{label:'Official resource library',href:'/resources'}]}
};

export function generateStaticParams(){return Object.keys(sections).map(section=>({section}));}

export default async function Section({params}:{params:Promise<{section:string}>}){
 const {section}=await params;const item=sections[section];if(!item)notFound();const Icon=iconMap[item.icon as keyof typeof iconMap]||FileText;
 return <div className="workspace-content">
  <span className="eyebrow">YOUR WORKSPACE / {item.subtitle.toUpperCase()}</span>
  <h1 className="workspace-title">{item.title}</h1><p className="workspace-lead">{item.description}</p>
  <div className={styles.hero}><section className={styles.heroCard}><div className={styles.heroIcon}><Icon size={27}/></div><span className={styles.kicker}>HOW THIS WORKS</span><h2 className={styles.title}>Start with the outcome. Build the pathway.</h2><p className={styles.lead}>{item.summary}</p></section><aside className={styles.sideCard}><ShieldCheck size={22}/><h3>Guided preparation</h3><p>Te Ao Hou helps organise the pathway, evidence and next actions. Formal Court orders, legal decisions, council approvals and finance decisions remain with the authorised bodies.</p></aside></div>
  {item.goals.length>0&&<><div className={styles.sectionHead}><div><span className={styles.kicker}>CHOOSE WHERE TO START</span><h2>What are you trying to do?</h2></div><p>Pick the goal closest to your situation. You can change direction as the whenua record becomes clearer.</p></div><div className={styles.goalGrid}>{item.goals.map(g=>{const G=iconMap[g.icon as keyof typeof iconMap]||Compass;const card=<><div className={styles.goalTop}><div className={styles.goalIcon}><G size={21}/></div><ArrowRight size={18}/></div><h3>{g.title}</h3><p>{g.description}</p><span className={styles.action}>Explore pathway <ArrowRight size={14}/></span></>;return g.href?<Link className={styles.goalCard} href={g.href} key={g.title}>{card}</Link>:<div className={styles.goalCard} key={g.title}>{card}</div>})}</div></>}
  <div className={styles.sectionHead}><div><span className={styles.kicker}>YOUR PATHWAY</span><h2>Stages to work through</h2></div><p>Each stage becomes a case checklist once secure client intake is enabled.</p></div>
  <div className={styles.timeline}>{item.stages.map((s,i)=><article className={styles.stageCard} key={s.title}><div className={styles.stageRow}><div className={styles.stageNo}>{String(i+1).padStart(2,'0')}</div><div className={styles.stageBody}><h3>{s.title}</h3><p>{s.description}</p>{s.tags&&<div className={styles.stageMeta}>{s.tags.map(t=><span className={styles.tag} key={t}>{t}</span>)}</div>}{s.checks&&<div className={styles.checklist}>{s.checks.map(c=><div className={styles.checkItem} key={c}><span className={styles.checkDot}/><span>{c}</span></div>)}</div>}</div><div className={styles.stageArrow}><ArrowRight size={17}/></div></div></article>)}</div>
  <div className={styles.detailGrid}><section className={styles.detailCard}><span className={styles.kicker}>BRING WHAT YOU KNOW</span><h3 style={{marginTop:8}}>Useful starting information</h3><div className={styles.checklist}>{item.prepare.map(x=><div className={styles.checkItem} key={x}><CheckCircle2 size={16} color="#7851a9"/><span>{x}</span></div>)}</div></section><section className={styles.detailCard}><span className={styles.kicker}>KEY QUESTIONS</span><h3 style={{marginTop:8}}>Decisions to resolve</h3><div className={styles.checklist}>{item.decisions.map(x=><div className={styles.checkItem} key={x}><span className={styles.checkDot}/><span>{x}</span></div>)}</div></section></div>
  {item.warning&&<div className={styles.warning}><AlertTriangle size={18}/><span>{item.warning}</span></div>}
  <div className={styles.sectionHead}><div><span className={styles.kicker}>OFFICIAL SOURCES</span><h2>Check the current requirements</h2></div><p>Forms and processes can change. Always verify the current official source before filing or relying on a requirement.</p></div><section className={styles.detailCard}>{item.resources.map(r=>r.href.startsWith('/')?<Link className={styles.resourceLink} href={r.href} key={r.label}><span>{r.label}</span><ArrowRight size={16}/></Link>:<a className={styles.resourceLink} href={r.href} target="_blank" rel="noopener noreferrer" key={r.label}><span>{r.label}</span><ExternalLink size={16}/></a>)}<Link className={styles.resourceLink} href="/resources"><span>Open the full Te Ao Hou resource library</span><ArrowRight size={16}/></Link></section>
 </div>
}
